python run_qa_electra.py \
  --model_name_or_path google/electra-large-discriminator \
  --dataset_name cuad \
  --do_train \
  --do_predict \
  --per_device_train_batch_size 16 \
  --learning_rate 3e-5 \
  --num_train_epochs 2 \
  --max_seq_length 512 \
  --max_answer_length 512 \
  --doc_stride 256 \
  --output_dir ./train_models/electra-large \
  --overwrite_output_dir \
  --save_steps 10000 \
  --version_2_with_negative