python3 run_qa.py \
  --model_name_or_path bert-base-uncased \
  --dataset_name cuad \
  --do_train \
  --do_predict \
  --per_device_train_batch_size 16 \
  --per_device_eval_batch_size 16 \
  --learning_rate 1e-5 \
  --num_train_epochs 6 \
  --max_seq_length 512 \
  --max_answer_length 512 \
  --doc_stride 256 \
  --output_dir ../train_models/bert-base \
  --overwrite_output_dir \
  --save_steps 10000 \
  --version_2_with_negative
